(() => {
  const DASHBOARD='https://script.google.com/macros/s/AKfycbzE26z7tcEbnwLPKSLLW8H_rK7UqwKV17rV8YBJVT4lB4slY0qorsf8cL4cnsys5ShGhw/exec';
  const REPO='https://github.com/Jchernand3z19/Portafolio/tree/main/mundial-2026-predicciones';
  const BUILD='20260722-1801';
  const preview=['assets/mundial/resumen-01.txt','assets/mundial/resumen-02.txt','assets/mundial/resumen-03.txt'];
  const apps=[
    ['Code.gs','Servidor y acceso a datos','Publica el Web App, lee las hojas históricas y predictivas y entrega al navegador los objetos que utiliza el dashboard.','Solicitud web y tablas de Google Sheets.','HTML evaluado y colecciones de datos.','Los IDs reales fueron sustituidos por marcadores; no se publican credenciales.',['assets/code/apps-script/Code.gs.txt.gz.b64']],
    ['index.html','Estructura visual','Define navegación, filtros, indicadores, gráficos, tablas y contenedores de predicción.','Plantilla de Apps Script e información preparada por Code.gs.','DOM base de todas las vistas.','El recurso Base64 interno fue reemplazado por un marcador.',['assets/code/apps-script/index.html.txt.gz.b64']],
    ['style.html','Diseño responsive','Contiene colores, tipografía, tarjetas, tablas, bracket y reglas para computadora y móvil.','Clases y elementos de index.html.','Presentación completa del dashboard.','No contiene credenciales; el recurso interno fue saneado.',['assets/code/apps-script/style.html.txt.gz.b64.part01','assets/code/apps-script/style.html.txt.gz.b64.part02','assets/code/apps-script/style.html.txt.gz.b64.part03','assets/code/apps-script/style.html.txt.gz.b64.part04']],
    ['script.html','Lógica y visualizaciones','Carga datos, normaliza estructuras, aplica filtros y dibuja métricas, gráficos, tablas y predicciones.','Respuesta de getDashboardData() y acciones del usuario.','Dashboard interactivo actualizado.','La versión publicada está saneada y omite datos privados.',['assets/code/apps-script/script.html.txt.gz.b64.part01','assets/code/apps-script/script.html.txt.gz.b64.part02','assets/code/apps-script/script.html.txt.gz.b64.part03']]
  ];
  const pyBase='https://raw.githubusercontent.com/Jchernand3z19/Portafolio/main/';
  const ghBase='https://github.com/Jchernand3z19/Portafolio/blob/main/';
  const python=[
    ['01_prediccion_dinamica_2026.py','Modelo predictivo inicial','Carga calendario, ranking y estadísticas; calcula fortalezas, goles esperados y probabilidades para simular grupos y eliminatorias.','Calendario, ranking, Elo y forma reciente.','Predicción inicial completa.','Las credenciales se obtienen desde variables de entorno.','mundial-2026-predicciones/scripts/01_prediccion_dinamica_2026.py'],
    ['04_crear_fact_partidos_prediccion_2026.py','Tabla maestra del torneo','Une calendario, predicción inicial, predicción viva y resultados reales en una sola tabla.','Calendario y tablas predictivas.','fact_partidos_prediccion_2026.','El ID y las credenciales se reciben desde el entorno.','mundial-2026-predicciones/scripts/04_crear_fact_partidos_prediccion_2026.py'],
    ['src/config.py','Configuración por entorno','Centraliza nombres de tablas, versión del modelo y variables requeridas por el pipeline.','Variables de entorno y GitHub Secrets.','Configuración validada.','No guarda secretos; solo los lee del entorno.','mundial-2026-predicciones/src/config.py'],
    ['src/sheets_client.py','Cliente de Google Sheets','Encapsula autenticación y operaciones de lectura, escritura y anexado de DataFrames.','Cuenta de servicio, ID y nombre de hoja.','DataFrames y hojas actualizadas.','Llave privada y correo de servicio permanecen en el entorno.','mundial-2026-predicciones/src/sheets_client.py'],
    ['prediccion_viva_mundial_2026.yml','Ejecución programada','Automatiza la instalación de dependencias y la actualización periódica de la predicción viva.','Código del repositorio y secretos configurados.','Ejecución programada del pipeline.','Los secretos se referencian por nombre y no se imprimen.','.github/workflows/prediccion_viva_mundial_2026.yml']
  ];
  const cache=new Map();
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const getText=async url=>{const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=${BUILD}`);if(!r.ok)throw new Error(`No se pudo cargar ${url}`);return r.text()};
  const bytes=b64=>{const b=atob(b64.replace(/\s+/g,'')),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a};
  async function gunzip(b64){if(!('DecompressionStream'in window))throw new Error('El navegador no permite descomprimir este archivo.');const stream=new Blob([bytes(b64)]).stream().pipeThrough(new DecompressionStream('gzip'));return new Response(stream).text()}
  async function loadApp(f){const key=`a:${f[0]}`;if(cache.has(key))return cache.get(key);const text=await gunzip((await Promise.all(f[6].map(getText))).join(''));cache.set(key,text);return text}
  async function loadPy(f){const key=`p:${f[0]}`;if(cache.has(key))return cache.get(key);const text=await getText(pyBase+f[6]);cache.set(key,text);return text}
  function card(){return `<article class="card mw-card fade-in is-visible"><button class="mw-card__media" id="mw-open-media" type="button" aria-label="Ver proyecto Mundial 2026"><img id="mw-card-image" alt="Resumen del dashboard Mundial 2026" loading="lazy" decoding="async"><span class="mw-card__label">Dashboard real · Google Apps Script</span></button><div class="mw-card__body"><div class="mw-tags"><span class="mw-tag">Python</span><span class="mw-tag">Google Apps Script</span><span class="mw-tag">Google Sheets</span><span class="mw-tag">Chart.js</span></div><h3>Mundial 2026: análisis histórico y predicción</h3><p>Proyecto integral que combina preparación de datos, análisis histórico, modelado predictivo, automatización diaria y una experiencia web interactiva.</p><div class="mw-actions"><button class="mw-btn" id="mw-open" type="button">Ver proyecto completo</button><a class="mw-btn mw-btn--ghost" href="${DASHBOARD}" target="_blank" rel="noopener">Abrir dashboard</a><a class="mw-btn mw-btn--ghost" href="${REPO}" target="_blank" rel="noopener">Ver código</a></div></div></article>`}
  function view(){return `<section class="mw-view" id="mw-view" hidden role="dialog" aria-modal="true" aria-labelledby="mw-title"><div class="mw-top"><div class="mw-top__inner"><div class="mw-brand">JC HERNANDEZ</div><button class="mw-close" id="mw-close" type="button">Cerrar</button></div></div><main class="mw-shell"><div class="mw-breadcrumb"><button id="mw-back-top" type="button">Proyectos</button><span>/</span><span>Mundial 2026</span></div><header class="mw-hero"><div><p class="mw-kicker">Proyecto destacado</p><h2 id="mw-title">Mundial 2026: análisis histórico y predicción</h2><p>Una solución de datos de extremo a extremo: integra estadísticas históricas, genera predicciones iniciales y vivas, automatiza actualizaciones y publica los resultados en un dashboard web.</p></div><div class="mw-hero__actions"><a class="mw-btn" href="${DASHBOARD}" target="_blank" rel="noopener">Abrir dashboard</a><a class="mw-btn mw-btn--ghost" href="${REPO}" target="_blank" rel="noopener">Repositorio</a></div></header>
  <section class="mw-section"><div class="mw-section__head"><h3>Objetivo del proyecto</h3><p>Convertir múltiples fuentes deportivas en un producto analítico claro, reproducible y actualizable.</p></div><div class="mw-objective"><div class="mw-panel"><h4>Problema abordado</h4><p>La información histórica, el calendario 2026, el ranking y los resultados recientes estaban distribuidos en estructuras diferentes. El proyecto los normaliza, valida y conecta con un modelo predictivo y una interfaz de consulta.</p></div><div class="mw-metrics"><div class="mw-metric"><strong>7</strong><span>Mundiales</span></div><div class="mw-metric"><strong>448</strong><span>Partidos</span></div><div class="mw-metric"><strong>69</strong><span>Selecciones</span></div></div></div></section>
  <section class="mw-section"><div class="mw-section__head"><h3>Dashboard interactivo en calidad original</h3><p>La aplicación real se presenta directamente para evitar capturas comprimidas. Utiliza su menú lateral para navegar entre las cuatro vistas.</p></div><div class="mw-live-guide"><article><strong>Resumen histórico</strong><span>Indicadores, campeones, goles y disciplina.</span></article><article><strong>Selecciones históricas</strong><span>Participaciones, resultados y mejores ediciones.</span></article><article><strong>Predicción inicial 2026</strong><span>Escenario base de grupos y eliminatorias.</span></article><article><strong>Predicción viva 2026</strong><span>Resultados confirmados y partidos pendientes.</span></article></div><div class="mw-live"><div class="mw-live__bar"><strong>Dashboard Mundial 2026</strong><a href="${DASHBOARD}" target="_blank" rel="noopener">Abrir en una pestaña nueva</a></div><iframe src="${DASHBOARD}" title="Dashboard interactivo Mundial 2026" loading="lazy" allowfullscreen></iframe></div></section>
  <section class="mw-section"><div class="mw-section__head"><h3>Proceso de desarrollo</h3><p>Del dato bruto al dashboard publicado.</p></div><div class="mw-process"><div class="mw-step"><span class="mw-step__n">1</span><h4>Integración</h4><p>Históricos, calendario, ranking y resultados recientes.</p></div><div class="mw-step"><span class="mw-step__n">2</span><h4>Preparación</h4><p>Limpieza, homologación y validación de campos.</p></div><div class="mw-step"><span class="mw-step__n">3</span><h4>Predicción</h4><p>Modelo Poisson ajustado por ranking, Elo y forma.</p></div><div class="mw-step"><span class="mw-step__n">4</span><h4>Publicación</h4><p>Apps Script, Chart.js y GitHub Actions.</p></div></div></section>
  <section class="mw-section"><div class="mw-section__head"><h3>Arquitectura técnica</h3><p>Componentes principales y flujo de información.</p></div><div class="mw-architecture"><div class="mw-node"><b>Fuentes</b>Históricos y ranking</div><div class="mw-node"><b>Python</b>Limpieza y modelo</div><div class="mw-node"><b>Google Sheets</b>Tablas y snapshots</div><div class="mw-node"><b>Apps Script</b>Servicio y frontend</div><div class="mw-node"><b>Chart.js</b>Visualización web</div></div></section>
  <section class="mw-section"><div class="mw-section__head"><h3>Código completo y explicado</h3><p>Selecciona un archivo. Primero se explica su función y después aparece el contenido completo con desplazamiento vertical y horizontal.</p></div><div class="mw-code-tabs"><button class="mw-code-tab is-active" data-code="apps" type="button">Google Apps Script</button><button class="mw-code-tab" data-code="python" type="button">Python y automatización</button></div><div class="mw-code"><aside class="mw-files" id="mw-files"></aside><div class="mw-editor"><div class="mw-file-info"><p class="mw-info-label">Archivo seleccionado</p><h4 id="mw-info-title"></h4><p id="mw-info-description"></p><div class="mw-info-grid"><div><strong>Entrada</strong><span id="mw-info-input"></span></div><div><strong>Salida</strong><span id="mw-info-output"></span></div><div><strong>Seguridad</strong><span id="mw-info-security"></span></div></div></div><div class="mw-editor__bar"><div class="mw-editor__identity"><div class="mw-editor__dots" aria-hidden="true"><span></span><span></span><span></span></div><span id="mw-code-name"></span></div><div><a id="mw-code-source" target="_blank" rel="noopener" hidden>Ver en GitHub</a><button class="mw-copy" id="mw-copy" type="button">Copiar código completo</button></div></div><div class="mw-codebox" id="mw-code-content" tabindex="0">Selecciona un archivo.</div></div></div></section>
  <section class="mw-section"><div class="mw-section__head"><h3>Resultados</h3><p>Un caso que demuestra análisis, automatización y desarrollo de producto de datos.</p></div><div class="mw-results"><div class="mw-result"><strong>3,953</strong><p>Jugadores integrados.</p></div><div class="mw-result"><strong>1,136</strong><p>Goles analizados.</p></div><div class="mw-result"><strong>Diario</strong><p>Actualización preparada.</p></div></div><div class="mw-actions" style="margin-top:24px"><button class="mw-btn mw-btn--ghost" id="mw-back-bottom" type="button">Volver a proyectos</button></div></section></main></section>`}
  const list=kind=>kind==='apps'?apps:python;
  let currentKind='apps',currentText='';
  function buttons(kind,index=0){const box=document.getElementById('mw-files'),files=list(kind);box.innerHTML=files.map((f,i)=>`<button class="mw-file${i===index?' is-active':''}" data-i="${i}" type="button"><strong>${esc(f[0])}</strong><span>${esc(f[1])}</span></button>`).join('');box.querySelectorAll('.mw-file').forEach(b=>b.onclick=()=>show(kind,+b.dataset.i))}
  function info(f,kind){document.getElementById('mw-info-title').textContent=f[0];document.getElementById('mw-info-description').textContent=f[2];document.getElementById('mw-info-input').textContent=f[3];document.getElementById('mw-info-output').textContent=f[4];document.getElementById('mw-info-security').textContent=f[5];document.getElementById('mw-code-name').textContent=f[0];const a=document.getElementById('mw-code-source');if(kind==='python'){a.href=ghBase+f[6];a.hidden=false}else{a.hidden=true;a.removeAttribute('href')}}
  function renderCode(text){const code=document.getElementById('mw-code-content');const lines=text.split('\n');code.innerHTML=lines.map((line,i)=>`<div class="code-line"><span class="line-num">${i+1}</span><span class="line-content">${esc(line)}</span></div>`).join('')}
  async function show(kind,index){currentKind=kind;const f=list(kind)[index]||list(kind)[0];buttons(kind,index);info(f,kind);const code=document.getElementById('mw-code-content');code.textContent='Cargando archivo completo...';currentText='';try{currentText=kind==='apps'?await loadApp(f):await loadPy(f);renderCode(currentText)}catch(e){console.error(e);code.textContent=`No fue posible cargar el archivo completo.\n\n${e.message}`}}
  function open(){const v=document.getElementById('mw-view');v.hidden=false;document.body.style.overflow='hidden';v.scrollTop=0;show(currentKind,0)}
  function close(){document.getElementById('mw-view').hidden=true;document.body.style.overflow='';document.getElementById('mw-open')?.focus()}
  function mount(){const grid=document.querySelector('#proyectos .projects-grid');if(!grid)return;grid.innerHTML=card();document.body.insertAdjacentHTML('beforeend',view());Promise.all(preview.map(getText)).then(p=>document.getElementById('mw-card-image').src=`data:image/webp;base64,${p.join('')}`).catch(console.error);['mw-open','mw-open-media'].forEach(id=>document.getElementById(id).onclick=open);['mw-close','mw-back-top','mw-back-bottom'].forEach(id=>document.getElementById(id).onclick=close);document.querySelectorAll('.mw-code-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mw-code-tab').forEach(x=>x.classList.toggle('is-active',x===b));show(b.dataset.code,0)});document.getElementById('mw-copy').onclick=async e=>{if(!currentText)return;await navigator.clipboard.writeText(currentText);const old=e.currentTarget.textContent;e.currentTarget.textContent='Código copiado';setTimeout(()=>e.currentTarget.textContent=old,1400)};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('mw-view').hidden)close()})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();
})();
